# Generated by Django 3.2.6 on 2021-08-15 11:55

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('TabiNyans', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Hotel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hotel_name', models.CharField(max_length=100, verbose_name='Hotel Name')),
                ('location_url', models.URLField(default='https://google.com', max_length=400, verbose_name='Google Maps URL')),
                ('address', models.CharField(max_length=100, verbose_name='Hotel Name')),
                ('logo', models.ImageField(blank=True, null=True, upload_to='logos/', verbose_name='Hotel Logo')),
                ('hours', models.CharField(blank=True, max_length=100, verbose_name='Open Hours')),
                ('price', models.CharField(blank=True, max_length=100, verbose_name='Nightly Price')),
                ('high_season', models.BooleanField(verbose_name='High Season Rates')),
                ('dogs', models.BooleanField(verbose_name='Dogs on Premises')),
                ('short_term', models.BooleanField(verbose_name='Short Term Available')),
                ('food', models.BooleanField(verbose_name='Food Available')),
                ('night_staff', models.BooleanField(verbose_name='24HR Staff')),
                ('specials', models.CharField(blank=True, max_length=200, verbose_name='Special Services')),
                ('extra', models.CharField(blank=True, max_length=200, verbose_name='Other Information')),
                ('images', models.ImageField(blank=True, null=True, upload_to='hotel_image/', verbose_name='Hotel Image')),
                ('admin_approved', models.BooleanField(default=False)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
                ('city', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='TabiNyans.city')),
                ('prefecture', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='TabiNyans.prefecture')),
            ],
        ),
    ]
