# Generated by Django 3.2.6 on 2021-08-16 13:12

from django.db import migrations, models
import django.db.models.deletion
import smart_selects.db_fields


class Migration(migrations.Migration):

    dependencies = [
        ('TabiNyans', '0002_hotel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hotel',
            name='address',
            field=models.CharField(max_length=100, verbose_name='Address'),
        ),
        migrations.AlterField(
            model_name='hotel',
            name='city',
            field=smart_selects.db_fields.ChainedForeignKey(chained_field='precture', chained_model_field='precture', on_delete=django.db.models.deletion.CASCADE, to='TabiNyans.city'),
        ),
    ]
