# Generated by Django 3.2.6 on 2021-08-17 12:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TabiNyans', '0005_review'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hotel',
            name='location_url',
            field=models.URLField(max_length=400, verbose_name='Google Maps URL'),
        ),
    ]
