# Generated by Django 3.2.6 on 2021-08-17 12:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TabiNyans', '0006_alter_hotel_location_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hotel',
            name='location_url',
            field=models.URLField(blank=True, max_length=400, null=True, verbose_name='Google Maps URL'),
        ),
    ]
