# Generated by Django 3.2.6 on 2021-08-17 12:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TabiNyans', '0007_alter_hotel_location_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='hotel',
            name='website_url',
            field=models.URLField(blank=True, max_length=400, null=True, verbose_name='Hotel Website'),
        ),
    ]
