# Generated by Django 3.2.6 on 2021-08-17 14:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TabiNyans', '0009_alter_review_hotel'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='admin_approved',
            field=models.BooleanField(default=False),
        ),
    ]
