# Generated by Django 3.2.6 on 2021-08-27 13:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('TabiNyans', '0011_likes'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Likes',
        ),
    ]
